basic.showIcon(IconNames.Heart)
music.setTempo(125)
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(587, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(784, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(784, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(880, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Quarter))
music.playTone(784, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(587, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
basic.forever(function () {
	
})
